version: '3.8'

services:
  postgresql:
    image: postgres:latest
    container_name: test_postgresql
    environment:
      POSTGRES_DB: test_data
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - ./database/data/postgresql:/var/lib/postgresql/data
      - ./database/etc/postgresql/initial.sql:/docker-entrypoint-initdb.d/initial.sql:ro